services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  dev-db:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin@123
      POSTGRES_DB: hedgify
    volumes:
      - postgres_data:/var/lib/postgresql/data

  hedgify-server:
    build:
      context: ./hedgify-server
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: ./
          target: /dist
          ignore:
            - node_modules/
            - .git/
        - action: rebuild
          path: package.json
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://postgres:admin@123@dev-db:5432/hedgify
    depends_on:
      - dev-db
      - redis

  # hedgify-client:
  #   build:
  #     context: ./hedgify-client
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - hedgify-server

volumes:
  redis_data:
  postgres_data:
